version: "3.9"

services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    privileged: true
    environment:
      - SHARED_DIRECTORY=/nfs
    volumes:
      - ./nfs-data:/nfs
    networks:
      - k3d-dev-cluster
    restart: unless-stopped

networks:
  k3d-dev-cluster:
    external: true
