apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd-image-updater
data:
  log.level: debug
  registries.conf: |
    registries:
      - name: Docker Hub
        api_url: https://registry-1.docker.io
        credentials: pullsecret:argocd/dockerhub-creds-image-2
        default: true
        defaultns: library